### ISSUE TITLE
Publish on maven repository

### ISSUE THREAD

**Issue by gyscos** [TheElectronWill/TOML-javalib#5]
For easy installation

**Comment by TheElectronWill** [comment]
I currently don't have the time to setup a dedicated maven repo nor to publish TOML-javalib to central. But it is available on [JitPack](https://jitpack.io/#TheElectronWill/TOML-javalib). I'll put a link in the README.

**Comment by TheElectronWill** [comment]
I don't work on this anymore, I've worked on a new config library with a common interface for several configuration formats (including TOML): https://github.com/TheElectronWill/night-config
