### ISSUE TITLE
Boolean types

### ISSUE THREAD

**Issue by ilevd** [TheElectronWill/TOML-javalib#6]
It seems boolean types are missing.
https://github.com/toml-lang/toml#user-content-boolean
Example:
```
a = true
b = false
```
TomlException Invalid value at line 1  com.electronwill.toml.TomlReader.nextValue (TomlReader.java:136)

**Comment by TheElectronWill** [comment]
Thanks for reporting this!
Actually they weren't missing but badly checked. I should have fixed that, tell me if the problem still happen.
